"""
Claude API Service.

Handles interaction with Anthropic's Claude API for diagnosis generation.
"""

from typing import Dict, Any, Optional
import logging
from app.config import settings
from app.models.responses import AnalysisResponse, RootCause, RecommendedAction

logger = logging.getLogger(__name__)


class ClaudeService:
    """
    Service for interacting with Claude API.

    Constructs prompts, calls Claude API, and parses responses.
    """

    def __init__(self):
        """Initialize Claude service."""
        self.api_key = settings.anthropic_api_key
        self.model = settings.claude_model
        self.max_tokens = settings.claude_max_tokens
        self.temperature = settings.claude_temperature

        logger.info(f"Claude Service initialized (model: {self.model})")

    async def analyze_case(
        self,
        form_data: Dict[str, Any],
        medical_context: str
    ) -> AnalysisResponse:
        """
        Analyze patient case using Claude API.

        Args:
            form_data: Patient form data from discovery call
            medical_context: Relevant medical knowledge from RAG

        Returns:
            Structured analysis response

        TODO: Implement actual Claude API call
        """
        logger.info("Analyzing case with Claude API (placeholder)")

        # Placeholder response
        # Will be replaced with actual Claude API call that uses:
        # 1. System prompt (medical AI assistant role)
        # 2. User message (form data + medical context)
        # 3. Structured output parsing

        return self._create_placeholder_response(form_data)

    def _create_placeholder_response(self, form_data: Dict[str, Any]) -> AnalysisResponse:
        """Create a placeholder response for testing."""

        # Determine basic diagnosis from form data
        main_issue = form_data.get("main_issue", "unknown")
        has_partner = form_data.get("relationship_status") in ["married", "in_relationship"]

        if main_issue == "ed":
            primary_diagnosis = "Erectile Dysfunction - Analysis Pending"
            root_causes = [
                RootCause(
                    category="Performance Anxiety",
                    confidence="medium",
                    explanation="Placeholder analysis - awaiting Claude API integration",
                    contributing_factors=["Form data collected", "Awaiting AI analysis"],
                    analogy="This is a placeholder response"
                )
            ]
        elif main_issue == "pe":
            primary_diagnosis = "Premature Ejaculation - Analysis Pending"
            root_causes = [
                RootCause(
                    category="Premature Ejaculation",
                    confidence="medium",
                    explanation="Placeholder analysis - awaiting Claude API integration",
                    contributing_factors=["Form data collected", "Awaiting AI analysis"]
                )
            ]
        else:
            primary_diagnosis = "Combined ED/PE - Analysis Pending"
            root_causes = []

        return AnalysisResponse(
            success=True,
            primary_diagnosis=primary_diagnosis,
            root_causes=root_causes,
            summary="This is a placeholder response. Claude API integration will provide actual root cause analysis based on form data and medical knowledge.",
            recommended_actions=[
                RecommendedAction(
                    action_type="system",
                    description="Claude API integration pending",
                    priority="high"
                )
            ],
            red_flags=[],
            requires_specialist=False,
            model_used=self.model,
            sources_used=["Placeholder - RAG not yet integrated"],
            detailed_analysis="Detailed analysis will be generated by Claude API once integrated.",
            conversation_starters=[
                "Form data received successfully",
                "Awaiting Claude API configuration"
            ]
        )

    def _build_system_prompt(self) -> str:
        """
        Build system prompt for Claude.

        Returns the role/instruction prompt for the AI.

        TODO: Refine based on testing
        """
        return """You are an expert medical AI assistant specializing in erectile dysfunction (ED) and premature ejaculation (PE) diagnosis.

Your role is to analyze patient discovery call data and identify root causes using evidence-based medical knowledge.

Key responsibilities:
1. Identify primary and contributing root causes
2. Explain causes in patient-friendly language
3. Use analogies to help patients understand
4. Flag any red flags requiring specialist referral
5. Recommend appropriate next steps

Always base your analysis on the medical knowledge provided and be accurate, empathetic, and clear."""

    def _build_user_prompt(
        self,
        form_data: Dict[str, Any],
        medical_context: str
    ) -> str:
        """
        Build user prompt containing form data and context.

        Args:
            form_data: Patient form data
            medical_context: Retrieved medical knowledge

        Returns:
            Formatted prompt string

        TODO: Optimize prompt structure
        """
        prompt_parts = [
            "Please analyze the following patient case:\n",
            "\n## PATIENT INFORMATION\n",
            self._format_form_data(form_data),
            "\n\n## RELEVANT MEDICAL KNOWLEDGE\n",
            medical_context,
            "\n\n## REQUESTED ANALYSIS\n",
            "Provide a structured root cause analysis including:",
            "1. Primary diagnosis",
            "2. Root causes with confidence levels",
            "3. Patient-friendly explanations with analogies",
            "4. Recommended actions",
            "5. Any red flags"
        ]

        return "\n".join(prompt_parts)

    def _format_form_data(self, form_data: Dict[str, Any]) -> str:
        """Format form data for prompt."""
        # Convert form data dictionary to readable format
        sections = []

        sections.append("Demographics:")
        sections.append(f"- Age: {form_data.get('age')} years")
        sections.append(f"- Main Concern: {form_data.get('main_issue', 'unknown').upper()}")

        if form_data.get('medical_conditions'):
            sections.append(f"\nMedical History: {', '.join(form_data.get('medical_conditions', []))}")

        # Add more sections as needed
        return "\n".join(sections)


# Global instance
claude_service = ClaudeService()
